[2024-11-20T17:50:05.951+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T17:50:05.970+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl_pipeline.load_reddit_data manual__2024-11-20T17:49:56.556606+00:00 [queued]>
[2024-11-20T17:50:05.980+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl_pipeline.load_reddit_data manual__2024-11-20T17:49:56.556606+00:00 [queued]>
[2024-11-20T17:50:05.981+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-20T17:50:05.993+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): load_reddit_data> on 2024-11-20 17:49:56.556606+00:00
[2024-11-20T17:50:06.002+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=917) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-20T17:50:06.004+0000] {standard_task_runner.py:72} INFO - Started process 919 to run task
[2024-11-20T17:50:06.005+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'reddit_etl_pipeline', 'load_reddit_data', 'manual__2024-11-20T17:49:56.556606+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp593ridn8']
[2024-11-20T17:50:06.006+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask load_reddit_data
[2024-11-20T17:50:06.060+0000] {task_command.py:467} INFO - Running <TaskInstance: reddit_etl_pipeline.load_reddit_data manual__2024-11-20T17:49:56.556606+00:00 [running]> on host 73e9d34b1ab9
[2024-11-20T17:50:06.365+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='reddit_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_reddit_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T17:49:56.556606+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T17:49:56.556606+00:00'
[2024-11-20T17:50:06.366+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T17:50:06.367+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T17:50:06.367+0000] {logging_mixin.py:190} INFO - Current task name:load_reddit_data state:running start_date:2024-11-20 17:50:05.971068+00:00
[2024-11-20T17:50:06.368+0000] {logging_mixin.py:190} INFO - Dag name:reddit_etl_pipeline and current dag run status:running
[2024-11-20T17:50:06.368+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T17:50:06.378+0000] {base.py:84} INFO - Retrieving connection 'reddit_connection'
[2024-11-20T17:50:06.382+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dags.py", line 64, in load_reddit_data
    conn = pg_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "172.18.0.3", port 5432 failed: FATAL:  database "reddit_db" does not exist

[2024-11-20T17:50:06.397+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T17:50:06.397+0000] {logging_mixin.py:190} INFO - Task start:2024-11-20 17:50:05.971068+00:00 end:2024-11-20 17:50:06.396696+00:00 duration:0.425628
[2024-11-20T17:50:06.398+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): load_reddit_data> dag:<DAG: reddit_etl_pipeline> dagrun:<DagRun reddit_etl_pipeline @ 2024-11-20 17:49:56.556606+00:00: manual__2024-11-20T17:49:56.556606+00:00, state:running, queued_at: 2024-11-20 17:49:56.581766+00:00. externally triggered: True>
[2024-11-20T17:50:06.398+0000] {logging_mixin.py:190} INFO - Failure caused by connection to server at "172.18.0.3", port 5432 failed: FATAL:  database "reddit_db" does not exist
[2024-11-20T17:50:06.399+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=reddit_etl_pipeline, task_id=load_reddit_data, run_id=manual__2024-11-20T17:49:56.556606+00:00, execution_date=20241120T174956, start_date=20241120T175005, end_date=20241120T175006
[2024-11-20T17:50:06.411+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T17:50:06.412+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 35 for task load_reddit_data (connection to server at "172.18.0.3", port 5432 failed: FATAL:  database "reddit_db" does not exist
; 919)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dags.py", line 64, in load_reddit_data
    conn = pg_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "172.18.0.3", port 5432 failed: FATAL:  database "reddit_db" does not exist

[2024-11-20T17:50:06.462+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T17:50:06.478+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T17:50:06.480+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
